name: CI

on:
  push:
    branches: [main]
    tags:
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    env:
      working-directory: ./
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Poetry
        uses: bakdata/ci-templates/actions/python-setup-poetry@v1.13.5
        with:
          python-version: ${{ matrix.python-version }}
          working-directory: ${{ env.working-directory }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint (ruff)
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" && "${{ matrix.python-version }}" == "3.10" ]]
          then
            echo "::add-matcher::.github/ruff-matcher.json"
            poetry run ruff check . --config pyproject.toml --output-format text --no-fix
          else
            poetry run pre-commit run ruff-lint --all-files --show-diff-on-failure
          fi;

      - name: Formatting (ruff)
        run: poetry run pre-commit run ruff-format --all-files --show-diff-on-failure

      - name: Typing (pyright)
        run: poetry run pre-commit run pyright --all-files

      - name: Test
        run: poetry run pytest tests
