name: Publish
# Template adapted from https://github.com/bakdata/ci-templates/tree/main/.github/workflows#python-poetry-release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Scope of the release; see https://python-poetry.org/docs/cli/#version"
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: release
    uses: bakdata/ci-templates/.github/workflows/python-poetry-release.yaml@1.45.2
    with:
      release-type: ${{ github.event.inputs.release-type }}
      publish-to-test: true
      python-version: "3.12"
      poetry-version: "1.8.2"
      # working-directory: "./"
    secrets:
      github-email: ${{ secrets.GH_EMAIL }}
      github-username: ${{ secrets.GH_USERNAME }}
      github-token: ${{ secrets.GH_TOKEN }}
      pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}

  print-version:
    name: print-version
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - run: echo "Bumped Version from ${{ needs.release.outputs.old-tag }} to ${{ needs.release.outputs.release-tag }}"
