name: Publish to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    uses: bakdata/ci-templates/.github/workflows/python-poetry-publish-pypi.yaml@1.48.0
    with:
      publish-to-test: false
      poetry-version: "1.8.2"
      python-version: "3.12"
    secrets:
      pypi-token: "${{ secrets.PYPI_TOKEN }}"
