name: Publish to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    uses: bakdata/ci-templates/.github/workflows/python-poetry-publish-pypi.yaml@1.46.3
    with:
      publish-to-test: false
      poetry-version: "2.1.3"
      python-version: "3.13"
    secrets:
      pypi-token: "${{ secrets.PYPI_TOKEN }}"
