name: Publish
# Template adapted from https://github.com/bakdata/ci-templates/tree/main/.github/workflows#python-poetry-release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Scope of the release; see https://python-poetry.org/docs/cli/#version"
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
    
jobs:
  release:
    name: release
    uses: bakdata/ci-templates/.github/workflows/python-poetry-release.yaml@v1.13.5
    with:
      release-type: ${{ github.event.inputs.release-type }}
      publish-to-test: true
      python-version: "3.10"
      # poetry-version: 1.3.2 # workflow likely wouldn't work with poetry-version < 1.2
      # working-directory: "./"
    secrets:
      github-email: ${{ secrets.GH_EMAIL }}
      github-username: ${{ secrets.GH_USERNAME }}
      github-token: ${{ secrets.GH_TOKEN }}
      pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}

  print-version:
    name: print-version
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - run: echo "Bumped Version from ${{ needs.publish.outputs.old-tag }} to ${{ needs.publish.outputs.release-tag }}"
